### ISSUE TITLE
复杂类型数据问题

### ISSUE THREAD

**Issue by rwson** [littleBlack520/ajax#3]
setData好像有点问题

```
{
      "obj": {
              "key": "value",
              "key2": "value"
       }
}
```

看setData是直接枚举该对象的第一层，调用value下的toString方法，Object类型的toString默认返回"[object Object]"，直接枚举第一层后调用toString可能导致后端收不到相关参数

**Comment by littleBlack520** [comment]
已经支持复杂的数据对象，感谢支持。
